#!/usr/bin/env node
/**
 * Self-host the UI fonts.
 *
 * Google's CSS endpoint splits each family into per-script woff2 files and pairs
 * them with `unicode-range`, so a Latin-only player never downloads the Cyrillic
 * glyphs (and vice-versa). We keep that structure and just re-point the URLs at
 * our own /fonts/ directory: no third-party request at runtime (Telegram
 * WebViews pay a cold DNS lookup for it), and the app keeps working offline.
 *
 * NOTE on family choice: Fredoka — the obvious "chunky game font" pick — has no
 * Cyrillic subset at all, so it cannot render Russian. Rubik is the closest
 * rounded display face that does. Both families are SIL OFL.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'client/public/fonts');

// A modern UA is required — with anything else Google serves legacy TTF, which
// is roughly 3x the size and has no unicode-range splitting.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/** Only these scripts ship; the game is EN + RU. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

/*
 * One VARIABLE family, not several static weights. Google serves the variable
 * cut as a single woff2 per subset spanning 500-900, so all four weights the UI
 * uses cost one download: 35 kB latin + 15 kB cyrillic. Requesting discrete
 * weights instead costs ~360 kB for the same coverage.
 *
 * Rubik doubles as the body face too — a second family would add ~60 kB for a
 * difference nobody would notice at 13px on a phone.
 */
const FAMILIES = [
  { css: 'Rubik:wght@500..900', name: 'Rubik' },
];

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const query = FAMILIES.map((f) => `family=${f.css}`).join('&');
  const res = await fetch(`https://fonts.googleapis.com/css2?${query}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
  const css = await res.text();

  // Each @font-face is preceded by a /* subset */ comment.
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error('no @font-face blocks parsed — did the CSS format change?');

  const out = [];
  const seen = new Set();
  let kept = 0, skipped = 0, bytes = 0;

  for (const [, subset, face] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) { skipped++; continue; }
    const url = face.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) { skipped++; continue; }

    const family = face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
    const weight = face.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
    const file = `${family.toLowerCase()}-${weight}-${subset}.woff2`;

    if (!seen.has(file)) {
      seen.add(file);
      const bin = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`download failed for ${file}: ${bin.status}`);
      const buf = Buffer.from(await bin.arrayBuffer());
      await writeFile(resolve(OUT_DIR, file), buf);
      bytes += buf.length;
      kept++;
    }
    out.push(`/* ${family} ${weight} — ${subset} */\n`
      // Relative, not /fonts/... — CSS resolves url() against the stylesheet,
      // so this survives a non-root deploy base (e.g. GitHub Pages /croyal/).
      + face.replace(/url\(https:[^)]+\.woff2\)/, `url(./${file})`));
  }

  const header = `/*\n * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n`
    + ` * ${FAMILIES.map((f) => f.name).join(' + ')}, SIL Open Font License 1.1.\n`
    + ` * Subsets: ${[...KEEP_SUBSETS].join(', ')} — Cyrillic only downloads for RU users.\n */\n\n`;
  await writeFile(resolve(OUT_DIR, 'fonts.css'), header + out.join('\n\n') + '\n');

  console.log(`fonts: ${kept} woff2 files, ${(bytes / 1024).toFixed(1)} kB total `
    + `(${skipped} blocks skipped as out-of-scope subsets)`);
  console.log(`wrote ${OUT_DIR}/fonts.css`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
